services:
  netbootxyz-cloud-init:
    build:
      context: .
      dockerfile: Dockerfile.cloud-init
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VERSION: ${VERSION:-latest}
    image: netbootxyz-cloud-init:latest
    container_name: netbootxyz-cloud-init
    restart: unless-stopped
    ports:
      - "3000:3000"    # Web UI
      - "69:69/udp"    # TFTP
      - "8080:80"      # HTTP for boot files and cloud-init
    volumes:
      - ./config:/config
      - ./assets:/assets
      - ./cloud-init-data:/cloud-init
    environment:
      - MENU_VERSION=2.0.76  # Specify menu version or leave empty for latest
      - NGINX_PORT=80
      - WEB_APP_PORT=3000
      - TFTPD_OPTS=--secure    # Additional TFTPD options
    networks:
      - netboot-network
    cap_add:
      - NET_ADMIN    # Required for TFTP
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  netboot-network:
    driver: bridge
