#cloud-config
# Monitoring Stack - Prometheus, Grafana, Node Exporter

# Update and upgrade packages
package_update: true
package_upgrade: true

# Install required packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - prometheus-node-exporter
  - nginx
  - certbot
  - python3-certbot-nginx

# Create monitoring user
users:
  - name: monitoring
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC... # Replace with your SSH public key

# Install and configure monitoring stack
runcmd:
  # Create directories
  - mkdir -p /etc/prometheus /var/lib/prometheus /etc/grafana /var/lib/grafana
  
  # Download and install Prometheus
  - |
    PROM_VERSION="2.45.0"
    curl -LO https://github.com/prometheus/prometheus/releases/download/v${PROM_VERSION}/prometheus-${PROM_VERSION}.linux-amd64.tar.gz
    tar xf prometheus-${PROM_VERSION}.linux-amd64.tar.gz
    cp prometheus-${PROM_VERSION}.linux-amd64/{prometheus,promtool} /usr/local/bin/
    cp -r prometheus-${PROM_VERSION}.linux-amd64/{consoles,console_libraries} /etc/prometheus/
    rm -rf prometheus-${PROM_VERSION}.linux-amd64*
  
  # Add Grafana repository and install
  - |
    curl -fsSL https://packages.grafana.com/gpg.key | gpg --dearmor -o /usr/share/keyrings/grafana.gpg
    echo "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://packages.grafana.com/oss/deb stable main" | tee /etc/apt/sources.list.d/grafana.list
    apt-get update
    apt-get install -y grafana
  
  # Set permissions
  - useradd --no-create-home --shell /bin/false prometheus
  - chown -R prometheus:prometheus /etc/prometheus /var/lib/prometheus /usr/local/bin/prometheus /usr/local/bin/promtool
  
  # Enable and start services
  - systemctl daemon-reload
  - systemctl enable prometheus grafana-server node_exporter
  - systemctl start prometheus grafana-server node_exporter
  
  # Configure Nginx reverse proxy
  - systemctl enable nginx
  - systemctl start nginx

# Write configuration files
write_files:
  - path: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s
        evaluation_interval: 15s
      
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        
        - job_name: 'node_exporter'
          static_configs:
            - targets: ['localhost:9100']
        
        - job_name: 'grafana'
          static_configs:
            - targets: ['localhost:3000']
    owner: prometheus:prometheus
    permissions: '0644'
  
  - path: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      
      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file /etc/prometheus/prometheus.yml \
        --storage.tsdb.path /var/lib/prometheus/ \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries
      
      [Install]
      WantedBy=multi-user.target
    permissions: '0644'
  
  - path: /etc/nginx/sites-available/monitoring
    content: |
      server {
        listen 80;
        server_name _;
        
        location / {
          proxy_pass http://localhost:3000;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /prometheus {
          proxy_pass http://localhost:9090;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    permissions: '0644'
  
  - path: /etc/grafana/provisioning/datasources/prometheus.yaml
    content: |
      apiVersion: 1
      
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://localhost:9090
          isDefault: true
    owner: grafana:grafana
    permissions: '0644'

# Configure system
bootcmd:
  - ln -sf /etc/nginx/sites-available/monitoring /etc/nginx/sites-enabled/monitoring
  - rm -f /etc/nginx/sites-enabled/default

# Set timezone
timezone: UTC

# Set hostname
hostname: monitoring-stack

# Final message
final_message: |
  Monitoring stack installation complete!
  
  Access points:
  - Grafana: http://$IP/ (admin/admin)
  - Prometheus: http://$IP/prometheus
  - Node Exporter metrics: http://$IP:9100/metrics
  
  Please change the Grafana admin password on first login! 